name: Deploy to WordPress Plugin Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Subversion
        run: |
          sudo apt-get update
          sudo apt-get install -y subversion rsync

      - name: Set variables
        run: |
          set -euo pipefail

          # Local vars (adjust if your plugin lives in a subfolder)
          PLUGIN_SLUG="llmagnet-llm-txt-generator"
          MAIN_FILE="llmagnet-ai-seo-optimizer.php"

          # Sanity check
          if [ ! -f "$MAIN_FILE" ]; then
            echo "Main plugin file not found at: $PWD/$MAIN_FILE"
            exit 1
          fi

          # Extract version from plugin header (handles optional leading '*' and spaces)
          VERSION=$(grep -Eim1 '^[[:space:]]*\*?[[:space:]]*Version:[[:space:]]*' "$MAIN_FILE" \
            | sed -E 's/.*Version:[[:space:]]*([^[:space:]]+).*/\1/' \
            | tr -d '\r')

          if [ -z "$VERSION" ]; then
            echo "Could not determine version from $MAIN_FILE"
            exit 1
          fi

          echo "PLUGIN_SLUG=$PLUGIN_SLUG" >> "$GITHUB_ENV"
          echo "MAIN_FILE=$MAIN_FILE" >> "$GITHUB_ENV"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "Determined plugin version: $VERSION"

      - name: Deploy to WordPress SVN
        env:
          SVN_USERNAME: ${{ secrets.WP_SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WP_SVN_PASSWORD }}
        run: |
          set -euo pipefail

          PLUGIN_SLUG="${{ env.PLUGIN_SLUG }}"
          VERSION="${{ env.VERSION }}"
          SVN_URL="https://plugins.svn.wordpress.org/$PLUGIN_SLUG"
          SVN_DIR="$PLUGIN_SLUG-svn"

          echo "SVN URL: $SVN_URL"
          echo "SVN checkout dir: $SVN_DIR"
          echo "Tagging version: $VERSION"

          # Checkout SVN repository
          svn checkout --username "$SVN_USERNAME" --password "$SVN_PASSWORD" "$SVN_URL" "$SVN_DIR" --non-interactive --trust-server-cert

          # Ensure base dirs
          mkdir -p "$SVN_DIR/trunk" "$SVN_DIR/assets" "$SVN_DIR/tags"

          # Move plugin asset images (if present) to /assets (SVN root)
          for file in banner-*.* icon*.* screenshot-*.*; do
            if [ -f "$file" ]; then
              mv "$file" "$SVN_DIR/assets/"
            fi
          done

          # Sync repo to trunk (clean)
          rsync -rc --delete \
            --exclude=".git" \
            --exclude=".github" \
            --exclude="node_modules" \
            --exclude="*.zip" \
            --exclude=".gitignore" \
            --exclude="$SVN_DIR" \
            --exclude="banner-*.*" \
            --exclude="icon*.*" \
            --exclude="screenshot-*.*" \
            ./ "$SVN_DIR/trunk/"

          # Abort if tag already exists
          if svn ls "$SVN_URL/tags/$VERSION" >/dev/null 2>&1; then
            echo "Tag $VERSION already exists. Bump the version in ${{ env.MAIN_FILE }} before deploying."
            exit 1
          fi

          # Create tag from trunk
          svn cp "$SVN_DIR/trunk" "$SVN_DIR/tags/$VERSION"

          # Stage changes
          cd "$SVN_DIR"
          svn status | grep '^!' | sed 's/^!//' | xargs -r svn delete
          svn status | grep '^?' | sed 's/^?//' | xargs -r svn add

          # Commit
          svn commit -m "Deploy version $VERSION" --username "$SVN_USERNAME" --password "$SVN_PASSWORD" --non-interactive --trust-server-cert
